# This is a basic workflow to help you get started with Actions

name: Azure Image Builder workflow for Managed image distribution

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:  [ .github/workflows/aib_workflow_mdi.yml ] 
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]
 
# workflow run is made up of steps to create and run Azure image builder to build custom images 
jobs:
  # This workflow contains a single job called "build"
  aib_template_job:
    name: define parameters and create Azure Image Builder template
    runs-on: ubuntu-latest
    env: 
      aib_template_name: "ubuntuignite01"
      aib_resource_group: "iblinuxgalleryRG"
        
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
      - name: azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'azure Image builder run to create managed image'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            curl https://raw.githubusercontent.com/lnochili/azvmimagebuilder/master/armTemplates/azplatform_image_deploy_mdi.json > ./template_mdi.json
            curl https://raw.githubusercontent.com/lnochili/azvmimagebuilder/master/armTemplates/azplatform_image_params_mdi.json > ./params_mdi.json
            az deployment group create --resource-group ${{ env.aib_resource_group }} --template-file ./template_mdi.json --parameters @./params_mdi.json --name ${{ env.aib_template_name }}
            az image builder run --resource-group ${{ env.aib_resource_group }}  --name ${{ env.aib_template_name }} 
  
            
